### ISSUE TITLE
It's cool terminal app.

### ISSUE THREAD

**Issue by bemoregt** [joshumax/csk-cli#1]
Hi, @joshumax 

It's cool terminal app.

Can I install for my mac OS X ?

**Comment by joshumax** [comment]
@bemoregt I don't see why not. I used it on a Mac a few months ago without any problems after installing node through Macports. If something doesn't work just create an issue and I'll work on getting it resolved.

**Comment by bemoregt** [comment]
How Can I install for it?

Is possible that install using home-brew also ?

Thanks reply.
