### ISSUE TITLE
Expired certificate error

### ISSUE THREAD

**Issue by ctwardy** [joshumax/csk-cli#6]
Hi! Looks like a great app, but where do I get a certificate? 
1. Installed via MacOS terminal

```
/Users/.../opt/anaconda3/lib
└─┬ csk-cli@1.0.1 
  ├─┬ cli-box@2.1.1 
  │ └── ansi-parser@1.3.0 
  ├─┬ couleurs@3.0.0 
  │ └── x256@0.0.2 
  ├─┬ follow-redirects@0.0.7 
  │ ├─┬ debug@2.6.9 
  │ │ └── ms@2.0.0 
  │ └── stream-consume@0.1.1 
  └── yesno@0.0.1 
```

2. First run:

```
(base) % csk
Error reading CSK key!
Please select one manually!
Enumerating charts...
Search for a Clear Sky Chart: centreville
...
```

Tried several searches finding some known sites but nothing quite near enough and then it crashed. 
 
3. Restart

```
% csk       
Error reading CSK key!
Please select one manually!
Enumerating charts...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: certificate has expired
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:609:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:439:38)
```

**Comment by joshumax** [comment]
I can't seem to reproduce this issue on Big Sur @ctwardy -- looking through the trace, perhaps cleardarksky.com was having certificate issues during this period of time? Let me know if it's still happening and I'll dig deeper.

**Comment by ctwardy** [comment]
OK - will try when I can.  In the meantime acknowledging you closed it as transitory / not reproducible.
