### ISSUE TITLE
Error reading CSK key!

### ISSUE THREAD

**Issue by bemoregt** [joshumax/csk-cli#7]
Hi, @joshumax 

I met thie error when run csk command.

"(base) user1@macPro ~ % csk
Error reading CSK key!
Please select one manually!
Enumerating charts...
Search for a Clear Sky Chart: "

What's wrong to me ?

Thanks
Best,
@bemoregt.

**Comment by joshumax** [comment]
Hi, nothing's wrong with that output as far as I can see. On first run the program looks for the presence of a .csk_key which references which clear sky chart you want loaded by default. If it is missing, it asks for you to search for a location to save in this file for all future queries.
